export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as PortfolioGrid } from './PortfolioGrid'
export { default as Testimonials } from './Testimonials'
export { default as Contact } from './Contact'
